## 1. Python List vs NumPy 속도 비교

In [3]:
# Python List vs NumPy 속도 비교
import time

# Python 리스트로 덧셈 (반복문 사용)
size = 1_000_000
list_a = list(range(size))
list_b = list(range(size))

start = time.time()
result_list = [a + b for a, b in zip(list_a, list_b)]
list_time = time.time() - start
print(f"Python List 덧셈 시간: {list_time:.4f}초")

Python List 덧셈 시간: 0.1050초


In [4]:
import numpy as np

# NumPy 배열로 덧셈 (벡터화 연산)
np_a = np.arange(size)
np_b = np.arange(size)

start = time.time()
result_np = np_a + np_b
np_time = time.time() - start
print(f"NumPy 배열 덧셈 시간: {np_time:.4f}초")
print(f"\nNumPy가 약 {list_time / np_time:.1f}배 빠름!")

NumPy 배열 덧셈 시간: 0.0047초

NumPy가 약 22.3배 빠름!


---
## 2. NumPy: 고성능 수치 연산의 표준

**Key Takeaway:** 내부적으로 C언어로 구현되어 압도적인 연산 속도를 제공하며, `ndarray`를 통해 다차원 데이터를 효율적으로 관리합니다.

### NumPy의 핵심 특징
- **빠른 속도:** Python 데이터 타입을 C 형식으로 변환 후 연산하여 속도 개선
- **`ndarray` 객체:** 다차원 배열을 위한 강력하고 효율적인 자료구조 (Pandas, TensorFlow의 기반)
- **벡터화 연산 (Vectorization):** 반복문 없이 배열 전체에 대한 동시 연산 지원
- **브로드캐스팅 (Broadcasting):** 크기가 다른 배열 간의 유연한 연산 지원

In [ ]:
# NumPy 설치 및 임포트
# !pip install numpy
import numpy as np

print(f"NumPy 버전: {np.__version__}")

---
## 3. NumPy의 핵심: `ndarray` (N-Dimensional Array)

In [5]:
# ndarray 생성 예제 (Diabetes 데이터셋 활용)
from sklearn.datasets import load_diabetes
import numpy as np

# 당뇨병 데이터셋 로드
diabetes = load_diabetes()

# 데이터의 일부를 ndarray로 변환 (처음 5개 샘플, 2개 특성)
data_slice = np.array(diabetes.data[:5, :2])

print(type(data_slice))  # <class 'numpy.ndarray'>
print(data_slice)

<class 'numpy.ndarray'>
[[ 0.03807591  0.05068012]
 [-0.00188202 -0.04464164]
 [ 0.08529891  0.05068012]
 [-0.08906294 -0.04464164]
 [ 0.00538306 -0.04464164]]


---
## 4. `ndarray` 해부하기: shape, ndim, size

`shape`, `ndim`, `size`는 배열의 구조를 파악하고 디버깅하는 데 필수적인 속성

- **`shape`:** 배열의 각 차원별 크기를 튜플로 반환 (가장 중요)
- **`ndim`:** 배열의 차원 수
- **`size`:** 배열에 있는 총 원소의 수 (`shape`의 모든 요소를 곱한 값)

In [6]:
# 예제 코드 (Diabetes 데이터셋)
X = diabetes.data  # 전체 데이터 로드 (442명의 환자, 10개의 특성)

print(f"Shape: {X.shape}")  # (442, 10)
print(f"Ndim: {X.ndim}")    # 2
print(f"Size: {X.size}")    # 4420

Shape: (442, 10)
Ndim: 2
Size: 4420


---
## 5. 데이터의 정체성: `dtype` (Data Type)

`ndarray`는 단일 `dtype`만 허용합니다. 데이터 타입은 메모리 효율성과 연산 정밀도를 결정합니다.

### 주요 숫자 `dtype`
| dtype | 설명 |
|-------|------|
| `bool` | Boolean (True, False) |
| `int32` | 32비트 정수 |
| `int64` | 64비트 정수 |
| `float32` | 32비트 부동 소수점 |
| `float64` | 64비트 부동 소수점 |

In [7]:
# 자료형 확인 및 변경 (astype)
X = diabetes.data

# 자료형 확인
print(f"Original Dtype: {X.dtype}")  # float64

# float64를 float32로 변경하여 메모리 사용량 감소
X_32 = X.astype(np.float32)
print(f"New Dtype: {X_32.dtype}")    # float32

# 메모리 사용량 비교
print(f"\nfloat64 메모리: {X.nbytes} bytes")
print(f"float32 메모리: {X_32.nbytes} bytes")
print(f"메모리 절약: {X.nbytes - X_32.nbytes} bytes ({(1 - X_32.nbytes/X.nbytes)*100:.0f}% 절감)")

Original Dtype: float64
New Dtype: float32

float64 메모리: 35360 bytes
float32 메모리: 17680 bytes
메모리 절약: 17680 bytes (50% 절감)


---
## 6. ndarray의 시작: 차원(Dimension)의 이해

ndarray는 1D, 2D, 3D, 4D... ND 등 다양한 차원을 가질 수 있으며,  
데이터 과학 및 머신러닝 분야에서는 주로 1D에서 4D까지의 배열이 사용

`ndarray.ndim` 속성을 사용하여 배열의 차원 수를 확인 가능

### 6-1. 1차원(1D) ndarray: 모든 배열의 기초 (Vector)

In [8]:
import numpy as np

nd1 = np.array([1, 2, 3, 4])
print(nd1)
print(f"ndim: {nd1.ndim}")
print(f"shape: {nd1.shape}")

[1 2 3 4]
ndim: 1
shape: (4,)


### 6-2. 2차원(2D) ndarray: 데이터 그리드의 형성 (Matrix)

In [9]:
nd2 = np.array([[1, 2, 3], [4, 5, 6]])

print(nd2)
print(f"ndim: {nd2.ndim}")
print(f"shape: {nd2.shape}")

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)


### 6-3. 3차원(3D)과 4차원(4D) ndarray: 공간으로의 확장 (Tensor)

In [10]:
# 3D Array
nd3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
                [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print("=== 3D Array ===")
print(nd3)
print(f"ndim: {nd3.ndim}")
print(f"shape: {nd3.shape}")

=== 3D Array ===
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
ndim: 3
shape: (2, 4, 3)


In [12]:
# 4D Array
nd4 = np.array([[[[1, 2], [3, 4], [5, 6], [7, 8]],
                 [[9, 10], [11, 12], [13, 14], [15, 16]]],

                [[[17, 18], [19, 20], [21, 22], [23, 24]],
                 [[25, 26], [27, 28], [29, 30], [31, 32]]]]) # Added missing sub-list
print("\n=== 4D Array ===")
print(nd4)
print(f"ndim: {nd4.ndim}")
print(f"shape: {nd4.shape}")


=== 4D Array ===
[[[[ 1  2]
   [ 3  4]
   [ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]
   [13 14]
   [15 16]]]


 [[[17 18]
   [19 20]
   [21 22]
   [23 24]]

  [[25 26]
   [27 28]
   [29 30]
   [31 32]]]]
ndim: 4
shape: (2, 2, 4, 2)


---
## 7. 배열의 청사진: `ndarray.shape`

머신러닝/딥러닝에서 입력 데이터의 shape를 맞추고 확인하는 과정은 매우 중요
`ndarray.shape`는 배열의 각 차원별 크기를 담은 파이썬 튜플(tuple)을 반환

| 차원 | 예시 배열 구조 | `shape` 결과 |
|------|---------------|-------------|
| 1D | [1 2 3 4] | (4,) |
| 2D | [[1 2 3], [4 5 6]] | (2, 3) |
| 3D | [[[1 2 3] [4 5 6]] [[7 8 9] [10 11 12]]] | (2, 4, 3) |
| 4D | ... | (3, 2, 2, 2) |

In [13]:
# shape 확인 실습
arr_1d = np.array([1, 2, 3, 4])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])

print(f"1D shape: {arr_1d.shape}")  # (4,)
print(f"2D shape: {arr_2d.shape}")  # (2, 3)
print(f"3D shape: {arr_3d.shape}")  # (2, 2, 3)

1D shape: (4,)
2D shape: (2, 3)
3D shape: (2, 2, 3)


---
## 8. 총 요소의 개수: `ndarray.size`

`ndarray.size`는 배열에 포함된 모든 요소(element)의 총 개수를 반환합니다.  
**Core Relationship:** `size`는 `shape` 튜플의 모든 값을 곱한 것과 같습니다.  
(size = shape[0] * shape[1] * ...)

In [14]:
# size 확인 실습
arrays = {
    "1D (4,)": np.array([1, 2, 3, 4]),
    "2D (2,3)": np.array([[1, 2, 3], [4, 5, 6]]),
    "3D (2,4,3)": nd3,
}

for name, arr in arrays.items():
    print(f"{name} → shape: {arr.shape}, size: {arr.size}")

1D (4,) → shape: (4,), size: 4
2D (2,3) → shape: (2, 3), size: 6
3D (2,4,3) → shape: (2, 4, 3), size: 24


---
## 9. 형태의 변환: `ndarray.reshape`

**Why Reshape?** 입력 데이터의 shape이 모델이 요구하는 것과 불일치할 경우,  
reshape을 통해 형태를 변환하는 과정이 필수

**The Golden Rule:** ndarray의 size가 동일해야 reshape이 가능

In [15]:
# reshape 실습
# 1D 배열 생성 (size: 24)
arr = np.arange(1, 25)  # [1, 2, 3, ..., 24]
print(f"원본: shape={arr.shape}, size={arr.size}")
print(arr)
print()

원본: shape=(24,), size=24
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [16]:
# (24,) → (6, 4) reshape
reshaped_2d = arr.reshape((6, 4))
print(f"reshape(6, 4): shape={reshaped_2d.shape}, size={reshaped_2d.size}")
print(reshaped_2d)
print()

reshape(6, 4): shape=(6, 4), size=24
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



In [17]:
# (24,) → (2, 4, 3) reshape
reshaped_3d = arr.reshape((2, 4, 3))
print(f"reshape(2, 4, 3): shape={reshaped_3d.shape}, size={reshaped_3d.size}")
print(reshaped_3d)

reshape(2, 4, 3): shape=(2, 4, 3), size=24
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [18]:
# -1을 사용한 자동 크기 계산
# (24,) → (4, -1) = (4, 6)
auto_reshaped = arr.reshape(4, -1)
print(f"reshape(4, -1): shape={auto_reshaped.shape}")
print(auto_reshaped)
print()

# size가 맞지 않으면 에러 발생
try:
    arr.reshape((5, 5))  # 25 != 24
except ValueError as e:
    print(f"에러 발생: {e}")

reshape(4, -1): shape=(4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

에러 발생: cannot reshape array of size 24 into shape (5,5)


---
## 10. 반복문 없는 연산의 힘: 벡터화 연산 (Vectorization)

ndarray는 별도의 반복문(for loop) 없이 배열의 같은 위치에 있는 요소끼리(element-wise)  
한 번에 연산 수행함으로써 코드의 간결성과 연산 속도를 극대화

In [19]:
# 벡터화 연산 실습
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [2, 2]])

print("A:")
print(A)
print("\nB:")
print(B)

A:
[[1 2]
 [3 4]]

B:
[[2 2]
 [2 2]]


In [20]:
# 덧셈
print("A + B =")
print(A + B)

A + B =
[[3 4]
 [5 6]]


In [21]:
# 뺄셈
print("A - B =")
print(A - B)

A - B =
[[-1  0]
 [ 1  2]]


In [22]:
# 곱셈 (element-wise)
print("A * B =")
print(A * B)

A * B =
[[2 4]
 [6 8]]


In [23]:
# 나눗셈
print("A / B =")
print(A / B)

A / B =
[[0.5 1. ]
 [1.5 2. ]]


---
## 11. 자동으로 형태를 맞추는 능력: 브로드캐스팅 (Broadcasting)

크기가 다른 배열 간 연산 시, NumPy는 연산이 가능한 형태로 작은 배열을  
자동 확장(복사)하여 연산을 수행

In [24]:
# 예제 1: 1D 배열 + 스칼라
# np.arange(3) + 5
result1 = np.arange(3) + 5
print("np.arange(3) + 5 =", result1)
# [0, 1, 2] + [5, 5, 5] = [5, 6, 7]

np.arange(3) + 5 = [5 6 7]


In [25]:
# 예제 2: 2D 배열 + 1D 배열
# np.ones((3, 3)) + np.arange(3)
result2 = np.ones((3, 3)) + np.arange(3)
print("np.ones((3, 3)) + np.arange(3) =")
print(result2)

np.ones((3, 3)) + np.arange(3) =
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [26]:
# 예제 3: 열 벡터 + 행 벡터
# np.arange(3).reshape((3, 1)) + np.arange(3)
col_vec = np.arange(3).reshape((3, 1))
row_vec = np.arange(3)

print(f"열 벡터 shape: {col_vec.shape}")
print(col_vec)
print(f"\n행 벡터 shape: {row_vec.shape}")
print(row_vec)

result3 = col_vec + row_vec
print(f"\n결과 shape: {result3.shape}")
print(result3)

열 벡터 shape: (3, 1)
[[0]
 [1]
 [2]]

행 벡터 shape: (3,)
[0 1 2]

결과 shape: (3, 3)
[[0 1 2]
 [1 2 3]
 [2 3 4]]
